default: &default
  dispatchers:
    - polling_interval: 100
      batch_size: 500
  workers:
    - queues: "*"
      threads: 7
      processes: 2
      polling_interval: 100

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
