default: &default
  dispatchers:
    - polling_interval: 10
      batch_size: 500
  workers:
    - queues: "*"
      threads: 5
      processes: 10
      polling_interval: 10

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
